// DEMO
var item1 = InventoryItemBefore.Create("SKU-001", 50);
item1.Display();

var item2 = InventoryItemAfter.Create("SKU-001", 50);
item2.Display();

Console.WriteLine("\n=== Partial Constructors Demo ===\n");
Console.WriteLine("BEFORE (C# 13 way - single constructor):");
Console.WriteLine("  • Constructor logic in one place");
Console.WriteLine("  • Hard to layer with generated code");
Console.WriteLine("\nAFTER (C# 14 way - partial constructors):");
Console.WriteLine("  • Constructor signature and body separated");
Console.WriteLine("  • Perfect for source generators and code layering");
Console.WriteLine("  • One part declares, another implements");
Console.WriteLine("\n✓ Both work the same!");

// BEFORE: Traditional constructor (all in one place)
class InventoryItemBefore
{
    public string SKU { get; set; }
    public int Quantity { get; set; }

    // Single constructor with all logic together
    private InventoryItemBefore(string sku, int qty)
    {
        SKU = sku;
        Quantity = qty;
    }

    public static InventoryItemBefore Create(string sku, int qty)
        => new(sku, qty);

    public void Display() => Console.WriteLine($"Item (Before): {SKU}, Qty: {Quantity}");
}

// AFTER: C# 14 Partial Constructors - Declaration Part
// This part declares the constructor signature (could be in generated code)
partial class InventoryItemAfter
{
    public string SKU { get; set; }
    public int Quantity { get; set; }

    // Defining declaration: Just the signature, no body
    // This could be auto-generated by a source generator
    public partial InventoryItemAfter(string sku, int qty);

    public static InventoryItemAfter Create(string sku, int qty)
        => new(sku, qty);

    public void Display() => Console.WriteLine($"Item (After):  {SKU}, Qty: {Quantity}");
}

// AFTER: C# 14 Partial Constructors - Implementation Part
// This part implements the constructor body (manual or generated)
// This could be in a different file (e.g., auto-generated or hand-written)
partial class InventoryItemAfter
{
    // Implementing declaration: Provides the actual constructor body
    // Matches signature from defining declaration above
    public partial InventoryItemAfter(string sku, int qty)
    {
        // Initialize properties
        SKU = sku;
        Quantity = qty;
        
        // Validation logic
        if (Quantity < 0)
            throw new ArgumentException("Quantity cannot be negative");
    }
}
